apiVersion: v1
kind: Service
metadata:
  name: gesture-frontend-service
spec:
  type: NodePort
  selector:
    app: gesture-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Optional fixed port on the host
